# API

Nå skal vi ta for oss hvordan aksessere en webside eller database gjennom et Application Programming Interface (API). Deretter foreta et API-kall med en query.

Et API muliggjør kommunikasjon mellom servere.

### Fordelen med API

Med API kan du lage spørringer som henter oppdaterte tall. API gjør det lettere å hente tall for videre analyse.

Det er mer fleksibelt og mer avansert enn å laste ned data fra et brukergrensensittet er bestemt av den som har laget nettsiden.

Det er lettere å tilpasse akkurat de data du trenger, og så lenge det er kontakt mellom deg (klient) og nettstedet (server) har du tilgang til dataene uten å måtte lagre lokalt.

### REST API

En Representational State Transfer ([REST](https://en.wikipedia.org/wiki/REST)) er en programvare-arkitektur som definerer kommunikasjon i et nettverk mellom *client* og *server* i et nettverk. Kommunikasjonen skjer gjennom et regelverk; hypertekstoverføringsprotokoll, Hyper Text Transfer Protocol (HTTP).

Forespørsler skjer gjennom `request` biblioteket som lar deg benytte en hypertekstoverføringsprotokoll i python miljøet.

Pythons [requests](https://pypi.org/project/requests/) er et brukervennlig bibliotek som 
tilgjengelig for intallasjon på Pypi:

$ python -m pip install requests

Metoden `.get()` brukes til en HTTP GET-forespørsel fra nettleseren din (klienten) til serveren gjennom nettstedets URL-adresse. Nettstedet gir et respons gjennom en statuskode. Kode 200 betyr at siden eksisterer og fungerer.

In [1]:
import pandas as pd

url = "https://www.ssb.no/statbank/sq/"

In [2]:
import pandas as pd
import requests

url = "https://data.ssb.no/api/v0/no/table/"

tables = requests.get(url).json()

df = pd.DataFrame(tables)

print(df)

    id type                              text
0   al    l                    Arbeid og lønn
1   bf    l              Bank og finansmarked
2   vf    l    Bedrifter, foretak og regnskap
3   be    l                        Befolkning
4   bb    l            Bygg, bolig og eiendom
5   ei    l                Energi og industri
6   he    l                             Helse
7   if    l                Inntekt og forbruk
8   in    l        Innvandring og innvandrere
9   js    l       Jord, skog, jakt og fiskeri
10  kf    l                  Kultur og fritid
11  nk    l  Nasjonalregnskap og konjunkturer
12  nm    l                    Natur og miljø
13  os    l                  Offentlig sektor
14  pp    l            Priser og prisindekser
15  sk    l   Sosiale forhold og kriminalitet
16  sv    l                          Svalbard
17  ti    l           Teknologi og innovasjon
18  tr    l             Transport og reiseliv
19  ud    l                         Utdanning
20  ut    l                   Utenriksøkonomi
21  va    l                              Valg
22  vt    l       Varehandel og tjenesteyting

In [3]:
import requests
api_url = "https://data.ssb.no/api/v0/no/table/ei/"
response = requests.get(api_url)
print(response.status_code)

print(response.json())

200
[{'id': 'ei01', 'type': 'l', 'text': 'Energi'}, {'id': 'ei02', 'type': 'l', 'text': 'Industri og bergverksdrift'}, {'id': 'ei03', 'type': 'l', 'text': 'Olje og gass'}]

In [4]:
import requests
api_url = "https://data.ssb.no/api/v0/no/table/ei/ei01/"
response = requests.get(api_url)
print(response.status_code)

print(response.json())

200
[{'id': 'elektrisitet', 'type': 'l', 'text': 'Elektrisitet'}, {'id': 'elkraftpris', 'type': 'l', 'text': 'Elektrisitetspriser'}, {'id': 'energibalanse', 'type': 'l', 'text': 'Produksjon og forbruk av energi, energibalanse og energiregnskap'}, {'id': 'energikomm', 'type': 'l', 'text': 'Energibruk i kommunene (opphørt)'}, {'id': 'entjeneste', 'type': 'l', 'text': 'Energibruk i tjenesteytende næringer (opphørt)'}, {'id': 'fjernvarme', 'type': 'l', 'text': 'Fjernvarme og fjernkjøling'}, {'id': 'husenergi', 'type': 'l', 'text': 'Energibruk i husholdningene'}, {'id': 'indenergi', 'type': 'l', 'text': 'Energibruk i industrien'}, {'id': 'kis', 'type': 'l', 'text': 'Investeringer i olje og gass, industri, bergverk og kraftforsyning'}, {'id': 'kraftnaring', 'type': 'l', 'text': 'Elektrisitetsnæringens økonomiske utvikling'}, {'id': 'naringer', 'type': 'l', 'text': 'Næringenes økonomiske utvikling'}, {'id': 'ogibkoms', 'type': 'l', 'text': 'Omsetning i olje og gass, industri, bergverk og kraftforsyning'}, {'id': 'pii', 'type': 'l', 'text': 'Produksjonsindeks for olje og gass, industri, bergverk og kraftforsyning'}, {'id': 'ppi', 'type': 'l', 'text': 'Produsentprisindeksen'}, {'id': 'vannmag', 'type': 'l', 'text': 'Vannmagasinenes fyllingsgrad (opphørt)'}, {'id': 'vppi', 'type': 'l', 'text': 'Vareprisindeks for industrinæringene (opphørt)'}]

In [5]:
import pandas as pd
import requests

url = "https://data.ssb.no/api/v0/no/table/ei/ei01/"

data = requests.get(url).json()

df = pd.DataFrame(data)

print(df)

               id type                                               text
0    elektrisitet    l                                       Elektrisitet
1     elkraftpris    l                                Elektrisitetspriser
2   energibalanse    l  Produksjon og forbruk av energi, energibalanse...
3      energikomm    l                   Energibruk i kommunene (opphørt)
4      entjeneste    l     Energibruk i tjenesteytende næringer (opphørt)
5      fjernvarme    l                         Fjernvarme og fjernkjøling
6       husenergi    l                        Energibruk i husholdningene
7       indenergi    l                            Energibruk i industrien
8             kis    l  Investeringer i olje og gass, industri, bergve...
9     kraftnaring    l        Elektrisitetsnæringens økonomiske utvikling
10       naringer    l                    Næringenes økonomiske utvikling
11       ogibkoms    l  Omsetning i olje og gass, industri, bergverk o...
12            pii    l  Produksjonsindeks for olje og gass, industri, ...
13            ppi    l                              Produsentprisindeksen
14        vannmag    l             Vannmagasinenes fyllingsgrad (opphørt)
15           vppi    l     Vareprisindeks for industrinæringene (opphørt)

In [6]:
import pandas as pd
import requests

url = "https://data.ssb.no/api/v0/no/table/ei/ei01/2"

data = requests.get(url).json()

#df = pd.DataFrame(data)

print(data)

{'error': 'Parameter error'}

In [7]:
df[df["text"].str.contains(
    "Produksjon",
    case=False,
    na=False
)][["id", "text"]]

               id                                               text
2   energibalanse  Produksjon og forbruk av energi, energibalanse...
12            pii  Produksjonsindeks for olje og gass, industri, ...

In [8]:
url = "https://data.ssb.no/api/v0/no/table/ei/ei01/energibalanse/"

data = requests.get(url).json()

df = pd.DataFrame(data)

print(df)
print(requests.get(url).json())

           id type                                               text
0  SBMENU8600    l                    Energi i Norge, energibalanse
1  SBMENU8601    l  Energi i norsk økonomisk aktivitet, energiregn...
2  SBMENU4028    l                                         Vedforbruk
3  SBMENU3280    l                                Avslutta tidsserier
[{'id': 'SBMENU8600', 'type': 'l', 'text': 'Energi i Norge, energibalanse  '}, {'id': 'SBMENU8601', 'type': 'l', 'text': 'Energi i norsk økonomisk aktivitet, energiregnskap  '}, {'id': 'SBMENU4028', 'type': 'l', 'text': 'Vedforbruk'}, {'id': 'SBMENU3280', 'type': 'l', 'text': 'Avslutta tidsserier'}]

In [9]:
df[df["text"].str.contains(
    "Solkraft",
    case=False,
    na=False
)][["id", "text"]]

Empty DataFrame
Columns: [id, text]
Index: []

In [10]:
import requests
api_url = "https://data.ssb.no/api/pxwebapi/v2/tables?query=solkraftproduksjon"
response = requests.get(api_url)
print(response.status_code)

200

In [11]:
metadata = response.json()
print(metadata)

{'language': 'no', 'tables': [{'id': '08307', 'label': '08307: Produksjon, import, eksport og forbruk av elektrisk kraft (GWh) 1950-2025', 'description': '', 'sortCode': '0000000330', 'updated': '2026-05-08T06:00:00Z', 'firstPeriod': '1950', 'lastPeriod': '2025', 'category': 'public', 'variableNames': ['statistikkvariabel', 'år'], 'source': 'Statistisk sentralbyrå', 'subjectCode': 'ei', 'timeUnit': 'Annual', 'paths': [[{'id': 'ei', 'label': 'Energi og industri', 'sortCode': '0000030'}, {'id': 'ei01', 'label': 'Energi', 'sortCode': '0000031'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000032'}, {'id': 'SBMENU4249', 'label': 'Tilgang og bruk av elektrisitet', 'sortCode': '0000000300'}], [{'id': 'sv', 'label': 'Svalbard', 'sortCode': '0000093'}, {'id': 'sv04', 'label': 'Næringsliv og teknologi', 'sortCode': '0000098'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000099'}, {'id': 'SBMENU4249', 'label': 'Tilgang og bruk av elektrisitet', 'sortCode': '0000000300'}]], 'links': [{'rel': 'self', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08307?lang=no'}, {'rel': 'alternate', 'hreflang': 'en', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08307?lang=en'}, {'rel': 'metadata', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08307/metadata?lang=no'}, {'rel': 'data', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08307/data?lang=no&outputFormat=json-stat2'}]}, {'id': '08308', 'label': '08308: Produksjon av elektrisk kraft, etter krafttype (GWh) (F) 2006-2025', 'description': '', 'sortCode': '0000000340', 'updated': '2026-05-08T06:00:00Z', 'firstPeriod': '2006', 'lastPeriod': '2025', 'category': 'public', 'variableNames': ['region', 'statistikkvariabel', 'år'], 'source': 'Statistisk sentralbyrå', 'subjectCode': 'ei', 'timeUnit': 'Annual', 'paths': [[{'id': 'ei', 'label': 'Energi og industri', 'sortCode': '0000030'}, {'id': 'ei01', 'label': 'Energi', 'sortCode': '0000031'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000032'}, {'id': 'SBMENU4249', 'label': 'Tilgang og bruk av elektrisitet', 'sortCode': '0000000300'}], [{'id': 'sv', 'label': 'Svalbard', 'sortCode': '0000093'}, {'id': 'sv04', 'label': 'Næringsliv og teknologi', 'sortCode': '0000098'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000099'}, {'id': 'SBMENU4249', 'label': 'Tilgang og bruk av elektrisitet', 'sortCode': '0000000300'}]], 'links': [{'rel': 'self', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08308?lang=no'}, {'rel': 'alternate', 'hreflang': 'en', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08308?lang=en'}, {'rel': 'metadata', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08308/metadata?lang=no'}, {'rel': 'data', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08308/data?lang=no&outputFormat=json-stat2'}]}], 'page': {'pageNumber': 1, 'pageSize': 20, 'totalElements': 2, 'totalPages': 1, 'links': []}, 'links': [{'rel': 'self', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/?lang=no&query=solkraftproduksjon&pagesize=20&pageNumber=1'}]}

In [12]:
import requests
api_url = "https://data.ssb.no/api/pxwebapi/v2/tables?query=title:Produksjon AND elektrisk AND kraft"
response = requests.get(api_url)
print(response.status_code)

200

In [13]:
metadata = response.json()
print(metadata)

{'language': 'no', 'tables': [{'id': '14093', 'label': '14093: Produksjon av elektrisk kraft, etter krafttype og prisområde (MWh) 2020M01-2026M08', 'description': '', 'sortCode': '0000000070', 'updated': '2026-09-15T06:00:00Z', 'firstPeriod': '2020M01', 'lastPeriod': '2026M08', 'category': 'public', 'variableNames': ['prisområde', 'statistikkvariabel', 'måned'], 'source': 'Statistisk sentralbyrå', 'subjectCode': 'ei', 'timeUnit': 'Monthly', 'paths': [[{'id': 'ei', 'label': 'Energi og industri', 'sortCode': '0000030'}, {'id': 'ei01', 'label': 'Energi', 'sortCode': '0000031'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000032'}, {'id': 'SBMENU6800', 'label': 'Månedlige tall', 'sortCode': '0000000010'}], [{'id': 'sv', 'label': 'Svalbard', 'sortCode': '0000093'}, {'id': 'sv04', 'label': 'Næringsliv og teknologi', 'sortCode': '0000098'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000099'}, {'id': 'SBMENU6800', 'label': 'Månedlige tall', 'sortCode': '0000000010'}]], 'links': [{'rel': 'self', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/14093?lang=no'}, {'rel': 'alternate', 'hreflang': 'en', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/14093?lang=en'}, {'rel': 'metadata', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/14093/metadata?lang=no'}, {'rel': 'data', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/14093/data?lang=no&outputFormat=json-stat2'}]}, {'id': '08307', 'label': '08307: Produksjon, import, eksport og forbruk av elektrisk kraft (GWh) 1950-2025', 'description': '', 'sortCode': '0000000330', 'updated': '2026-05-08T06:00:00Z', 'firstPeriod': '1950', 'lastPeriod': '2025', 'category': 'public', 'variableNames': ['statistikkvariabel', 'år'], 'source': 'Statistisk sentralbyrå', 'subjectCode': 'ei', 'timeUnit': 'Annual', 'paths': [[{'id': 'ei', 'label': 'Energi og industri', 'sortCode': '0000030'}, {'id': 'ei01', 'label': 'Energi', 'sortCode': '0000031'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000032'}, {'id': 'SBMENU4249', 'label': 'Tilgang og bruk av elektrisitet', 'sortCode': '0000000300'}], [{'id': 'sv', 'label': 'Svalbard', 'sortCode': '0000093'}, {'id': 'sv04', 'label': 'Næringsliv og teknologi', 'sortCode': '0000098'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000099'}, {'id': 'SBMENU4249', 'label': 'Tilgang og bruk av elektrisitet', 'sortCode': '0000000300'}]], 'links': [{'rel': 'self', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08307?lang=no'}, {'rel': 'alternate', 'hreflang': 'en', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08307?lang=en'}, {'rel': 'metadata', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08307/metadata?lang=no'}, {'rel': 'data', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08307/data?lang=no&outputFormat=json-stat2'}]}, {'id': '08308', 'label': '08308: Produksjon av elektrisk kraft, etter krafttype (GWh) (F) 2006-2025', 'description': '', 'sortCode': '0000000340', 'updated': '2026-05-08T06:00:00Z', 'firstPeriod': '2006', 'lastPeriod': '2025', 'category': 'public', 'variableNames': ['region', 'statistikkvariabel', 'år'], 'source': 'Statistisk sentralbyrå', 'subjectCode': 'ei', 'timeUnit': 'Annual', 'paths': [[{'id': 'ei', 'label': 'Energi og industri', 'sortCode': '0000030'}, {'id': 'ei01', 'label': 'Energi', 'sortCode': '0000031'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000032'}, {'id': 'SBMENU4249', 'label': 'Tilgang og bruk av elektrisitet', 'sortCode': '0000000300'}], [{'id': 'sv', 'label': 'Svalbard', 'sortCode': '0000093'}, {'id': 'sv04', 'label': 'Næringsliv og teknologi', 'sortCode': '0000098'}, {'id': 'elektrisitet', 'label': 'Elektrisitet', 'sortCode': '0000099'}, {'id': 'SBMENU4249', 'label': 'Tilgang og bruk av elektrisitet', 'sortCode': '0000000300'}]], 'links': [{'rel': 'self', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08308?lang=no'}, {'rel': 'alternate', 'hreflang': 'en', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08308?lang=en'}, {'rel': 'metadata', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08308/metadata?lang=no'}, {'rel': 'data', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08308/data?lang=no&outputFormat=json-stat2'}]}, {'id': '08266', 'label': '08266: Konjunkturbarometeret. Begrensende faktorer i produksjonen 1990K1-2026K2', 'description': '', 'sortCode': '0000000040', 'updated': '2026-07-22T06:00:00Z', 'firstPeriod': '1990K1', 'lastPeriod': '2026K2', 'category': 'public', 'variableNames': ['næring/varetype', 'referanseperiode', 'type justering', 'statistikkvariabel', 'kvartal'], 'source': 'Statistisk sentralbyrå', 'subjectCode': 'ei', 'timeUnit': 'Quarterly', 'paths': [[{'id': 'ei', 'label': 'Energi og industri', 'sortCode': '0000030'}, {'id': 'ei02', 'label': 'Industri og bergverksdrift', 'sortCode': '0000032'}, {'id': 'kbar', 'label': 'Konjunkturbarometer for industri og bergverk', 'sortCode': '0000033'}], [{'id': 'nk', 'label': 'Nasjonalregnskap og konjunkturer', 'sortCode': '0000066'}, {'id': 'nk02', 'label': 'Konjunkturer', 'sortCode': '0000068'}, {'id': 'kbar', 'label': 'Konjunkturbarometer for industri og bergverk', 'sortCode': '0000069'}]], 'links': [{'rel': 'self', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08266?lang=no'}, {'rel': 'alternate', 'hreflang': 'en', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08266?lang=en'}, {'rel': 'metadata', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08266/metadata?lang=no'}, {'rel': 'data', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/08266/data?lang=no&outputFormat=json-stat2'}]}, {'id': '10455', 'label': '10455: Solgt produksjon av varer for store juridiske enheter i industri, etter 8-sifret Prodcomkode 2008-2025', 'description': '', 'sortCode': '0000000030', 'updated': '2026-09-23T06:00:00Z', 'firstPeriod': '2008', 'lastPeriod': '2025', 'category': 'public', 'variableNames': ['prodcomkode', 'statistikkvariabel', 'år'], 'source': 'Statistisk sentralbyrå', 'subjectCode': 'ei', 'timeUnit': 'Annual', 'paths': [[{'id': 'ei', 'label': 'Energi og industri', 'sortCode': '0000030'}, {'id': 'ei02', 'label': 'Industri og bergverksdrift', 'sortCode': '0000032'}, {'id': 'vti', 'label': 'Vareproduksjon i industri og bergverksdrift', 'sortCode': '0000033'}]], 'links': [{'rel': 'self', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/10455?lang=no'}, {'rel': 'alternate', 'hreflang': 'en', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/10455?lang=en'}, {'rel': 'metadata', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/10455/metadata?lang=no'}, {'rel': 'data', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/10455/data?lang=no&outputFormat=json-stat2'}]}], 'page': {'pageNumber': 1, 'pageSize': 20, 'totalElements': 5, 'totalPages': 1, 'links': []}, 'links': [{'rel': 'self', 'hreflang': 'no', 'href': 'https://data.ssb.no/api/pxwebapi/v2/tables/?lang=no&query=title:Produksjon AND elektrisk AND kraft&pagesize=20&pageNumber=1'}]}

In [14]:
import requests
api_url = "https://data.ssb.no/api/v0/no/table/08307"
response = requests.get(api_url)
print(response.status_code)

200

Metoden .json() gir oss innholdet i repsonsen. Dette er metadata som gir data om dataen.

In [15]:
metadata = response.json()
print(metadata)

{'title': '08307: Produksjon, import, eksport og forbruk av elektrisk kraft (GWh), etter statistikkvariabel og år', 'variables': [{'code': 'ContentsCode', 'text': 'statistikkvariabel', 'values': ['ProdTotal', 'VannKraft', 'VindKraft', 'Solkraft', 'VarmeKraft', 'Import', 'Eksport', 'Bruttoforbruk', 'ForbrukKraftStasj', 'Pumpekraftforbruk', 'TapStatistDiff', 'Nettoforbruk'], 'valueTexts': ['Produksjon i alt', 'Vannkraftproduksjon', 'Vindkraftproduksjon', 'Solkraftproduksjon', 'Varmekraftproduksjon', 'Import', 'Eksport', 'Bruttoforbruk', 'Forbruk i kraftstasjonene (-2019)', 'Pumpekraftforbruk', 'Tap og statistisk differanse', 'Nettoforbruk']}, {'code': 'Tid', 'text': 'år', 'values': ['1950', '1955', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025'], 'valueTexts': ['1950', '1955', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025'], 'time': True}]}

I metadataen ser vi verider

In [16]:
type(metadata)

dict

In [17]:
print(list(metadata.keys()))

['title', 'variables']

In [18]:
type(metadata['title'])

str

In [19]:
type(metadata['variables'])

list

In [20]:
print(metadata["variables"][0])
print(metadata["variables"][1])

{'code': 'ContentsCode', 'text': 'statistikkvariabel', 'values': ['ProdTotal', 'VannKraft', 'VindKraft', 'Solkraft', 'VarmeKraft', 'Import', 'Eksport', 'Bruttoforbruk', 'ForbrukKraftStasj', 'Pumpekraftforbruk', 'TapStatistDiff', 'Nettoforbruk'], 'valueTexts': ['Produksjon i alt', 'Vannkraftproduksjon', 'Vindkraftproduksjon', 'Solkraftproduksjon', 'Varmekraftproduksjon', 'Import', 'Eksport', 'Bruttoforbruk', 'Forbruk i kraftstasjonene (-2019)', 'Pumpekraftforbruk', 'Tap og statistisk differanse', 'Nettoforbruk']}
{'code': 'Tid', 'text': 'år', 'values': ['1950', '1955', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025'], 'valueTexts': ['1950', '1955', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025'], 'time': True}

In [21]:
print(metadata["variables"][0].keys())
print(metadata["variables"][1].keys())

dict_keys(['code', 'text', 'values', 'valueTexts'])
dict_keys(['code', 'text', 'values', 'valueTexts', 'time'])

In [22]:
for var in metadata["variables"]:
    print(f"\nKode: {var['code']}")
    print(f"Tekst: {var['text']}")
    print(f"Antall verdier: {len(var['values'])}")

Kode: ContentsCode
Tekst: statistikkvariabel
Antall verdier: 12

Kode: Tid
Tekst: år
Antall verdier: 68

In [23]:
filtre = {
    var["code"]: var["values"]
    for var in metadata["variables"]
    if var["code"] in ["ContentsCode", "Tid"]
}

print(filtre)

{'ContentsCode': ['ProdTotal', 'VannKraft', 'VindKraft', 'Solkraft', 'VarmeKraft', 'Import', 'Eksport', 'Bruttoforbruk', 'ForbrukKraftStasj', 'Pumpekraftforbruk', 'TapStatistDiff', 'Nettoforbruk'], 'Tid': ['1950', '1955', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']}